language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install
  # codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
#  - codecept build

script:
  - ~/.composer/vendor/bin/codecept build
  - ~/.composer/vendor/bin/codecept run

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover