language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.2

matrix:
  fast_finish: true

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.0"

  - travis_retry composer install --dev --prefer-dist --no-interaction
  # codeception
  - travis_retry composer global require "codeception/codeception=2.*" "codeception/specify=*" "codeception/verify=*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database taxonomy_test;'
  - php ./tests/yii migrate --migrationPath=@nkostadinov/taxonomy/migrations --interactive=0

script:
  - ~/.composer/vendor/bin/codecept build
  - ~/.composer/vendor/bin/codecept run

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover