#!/usr/bin/env php
<?php

require(__DIR__ . '/../../../../vendor/autoload.php');
require(__DIR__ . '/../../../../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/unit.php');

$application = new yii\console\Application($config);

$exitCode = $application->run();
exit($exitCode);